### ISSUE TITLE
RFE: add geometry to HDAs parameter via multiple selection and/or gather selection child meshes

### ISSUE THREAD

**Issue by jjg1234** [sideeffects/HoudiniEngineForUnityv2#1]
Hi,

Is it possible to implement a way to add to the asset parameters UI a way to use the drag and drop like in the Bake UI?

And another thing related to this is the capacity to handle the childs of a GameObject (you put the parent in the list and it will process all the childs with mesh filters for example).

[example image](https://i.gyazo.com/b143b407f8e1fe82b725d3cd972f72e0.png)

Thank you for this great toollset.

Regards,
Jonathan Jérôme-Gerstch.

**Comment by SeelanV** [comment]
Hi,
Thanks for posting these. I've added both items to our internal RFEs. Will update when they have been added.

**Comment by SeelanV** [comment]
This feature has been added a while back.
