### ISSUE TITLE
The register input interface priority work correct?

### ISSUE THREAD

**Issue by watsonsong** [sideeffects/HoudiniEngineForUnityv2#13]
The blow code:
https://github.com/sideeffects/HoudiniEngineForUnity/blob/dc97e8e2501ca39c0416fde8b5021b25dad34e6a/Plugins/HoudiniEngineUnity/Scripts/Utility/HEU_InputUtility.cs#L83

`
for (int i = numInterfaces - 1; i >= 0; i--)
{
    if (_inputInterfaces[i] != null && _inputInterfaces[i].Priority <= inputInterface.Priority)
    {
        _inputInterfaces.Add(inputInterface);
        //Debug.LogFormat("Registered {0} at {1}. Total of {2}", inputInterface.GetType(), i, _inputInterfaces.Count);
        break;
    }
}
`

The inputInterface seems always added into the last but add to the  index i?

**Comment by dpernuit** [comment]
Hi,
Corrrect - for some reason - input priority was ignored and the interface always added last.
I just fixed this - it will be available in tomorrow's daily build.
