### ISSUE TITLE
Typo in HEU_Parameters causing null reference exception ? 

### ISSUE THREAD

**Issue by ValentinBessonKlang** [sideeffects/HoudiniEngineForUnityv2#29]
Hello 

Is it intended that a for loop in SetStringParameterValues() loops IntValues[]'s length times ? I understand that a string parameter should indeed have its IntValues[] remaining null, hence failing.
Is it a typo or am I missing something ?

```
NullReferenceException: Object reference not set to an instance of an object
HoudiniEngineUnity.HEU_Parameters.SetStringParameterValues (System.String parameterName, System.String[] values, System.Boolean bRecookAsset) (at C:/klang/plastics/seed-art/art_source/tools/houdini/HEngine/HEUnity_pkg_SideFX/Scripts/Parameters/HEU_Parameters.cs:792)
```

**Comment by dpernuit** [comment]
Hi,
Thanks for bringing this up - yes you're right - the loop should have been using teh StringValues lenght instead.
I just fixed this - it will be available in tomorrow's daily build.
